//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakeStaff
    {
        public int ID { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string PName { get; set; }
        public string PDes { get; set; }
        public string PayPeriod { get; set; }
        public Nullable<decimal> PayRate { get; set; }
        public string EmailAddress { get; set; }
    }
}
